### PR TITLE
Technology Broker Icon

### PR DESCRIPTION
**Pull request by controllerface**
I needed to generate an icon for technology brokers to use in my app. This is the icon that shows up in the station services menus to indicate a tech broker.

It may not be 100% pixel accurate to the in game UI, but I think I got it very close. The image is 350px by 350px, but it that is too small I can scale it up.

### CODE REVIEW

**Comment by SpyTec** [comment]
Looks good, not seen the in game one but I'll trust you 🙂

You don't happen to have a vector as well do you?

**Comment by controllerface** [comment]
I don't unfortunately, just whipped this PNG up in gimp. I actually use a raw SVG path _generated_ from this image in my app, but the output I use doesn't display correctly in a browser so i decided not to upload it. If I get it in the proper format, i'll open another PR with it.

**Comment by controllerface** [comment]
Figured out the SVG thing so added a vector version as well. Cleaned up the source image so re-exported the PNG too. 

And for reference (in case you're curious) this reddit thread has a screenshot that has the icon in it, albeit a little blurry: https://www.reddit.com/r/EliteDangerous/comments/7rc8zk/tech_broker/
The icon is just to the right of the tech broker NPC portrait.

**Comment by SpyTec** [comment]
The SVG has a lot of whitespace around the vector, feel free to fix that up in a following PR. Merging this :)

**Pull request merged**
